export enum ModalType {
  NONE = 'NONE',
  DEPOSIT = 'DEPOSIT',
  REVIEW = 'REVIEW',
  PROCESSING = 'PROCESSING',
  GENERATE_ZK_PROOF = 'GENERATE_ZK_PROOF',
  SUCCESS = 'SUCCESS',
  WITHDRAW = 'WITHDRAW',
  CONNECT = 'CONNECT',
  ACTIVITY_DETAILS = 'ACTIVITY_DETAILS',
  PA_DETAILS = 'PA_DETAILS',
}
